[project]
name = "any2ebook"
version = "0.1.0"
description = "Create epub files from a list of links"
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "ebooklib>=0.20",
    "pyyaml>=6.0.3",
    "readabilipy>=0.3.0",
    "requests>=2.32.5"
]

[project.scripts]
any2ebook = "any2ebook.any2ebook:main"

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "coverage>=7.13.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
    "ruff>=0.14.9",
    "types-pyyaml>=6.0.12.20260724",
    "types-requests>=2.33.0.20260712",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
